language: php
php:
- 7.2
branches:
  only:
  - prod
  - develop
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_script:
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk" ]; then export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release
  -c -s)"; echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" |
  sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list; curl https://packages.cloud.google.com/apt/doc/apt-key.gpg
  | sudo apt-key add - ; sudo apt-get update && sudo apt-get install google-cloud-sdk;
  fi
- tar -xzf credentials.tar.gz
- mv .env.
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
- gcloud config set project 'trim-technique-215502'
- gcloud auth activate-service-account --key-file client-secret.json
stages:
- name: prod
  if: branch = prod
- name: develop
  if: branch = develop
jobs:
  include:
  - stage: prod
    script:
    - mv .env.prod .env
    - gcloud compute scp --recurse $TRAVIS_BUILD_DIR pronosticon_quinielas@pronosticon:/var/www/html/pronosticon-temp
      --zone us-east1-b
    - gcloud compute ssh pronosticon_quinielas@pronosticon --zone us-east1-b -- '
      (sudo rm -rf /var/www/html/pronosticon || true) && 
      mv /var/www/html/pronosticon-temp /var/www/html/pronosticon && 
      cd /var/www/html/pronosticon && 
      sudo chmod -R 777 . && 
      composer install --no-interaction && 
      php artisan migrate --no-interaction'
  - stage: develop
    script:
    - mv .env.develop .env
    - gcloud compute scp --recurse $TRAVIS_BUILD_DIR pronosticon_quinielas@pronosticon:/var/www/html/pronosticon-dev-temp
      --zone us-east1-b
    - gcloud compute ssh pronosticon_quinielas@pronosticon --zone us-east1-b -- '
      (sudo rm -rf /var/www/html/pronosticon-dev || true) && 
      mv /var/www/html/pronosticon-dev-temp /var/www/html/pronosticon-dev && 
      cd /var/www/html/pronosticon-dev && 
      sudo chmod -R 777 . && 
      composer install --no-interaction && 
      php artisan migrate --no-interaction'
notifications: 
email:
  on_failure: change
  on_success: change
before_install:
  - openssl aes-256-cbc -K $encrypted_adea68ea33ee_key -iv $encrypted_adea68ea33ee_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d